<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>ACR.Application</AssemblyName>
        <RootNamespace>ACR.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Options" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ACR.Domain\ACR.Domain.csproj" />
    </ItemGroup>

</Project>